--liquibase formatted sql

--changeset andrei:KOMDEV-7692
--comment Soedinyaya
create table dev_util.person (person_id integer primary key generated by default as identity, person_name text not null); 
--changeset andrei:KOMDEV-7692-1 runOnChange:true
create TABLE dev_util.custt(id integer, names  text);
